lib/ffi/genius_api_ffi.dart, lib/ffi/genius_api_ffi.dart.backup
=> FFI for All functions for genius_api

lib/main.dart, lib/onboarding/view/wallet_creation_screen.dart, lib/theme/genius_wallet_colors.g.dart, lib/theme/genius_wallet_font_size.dart, lib/widgets/components/wallet_button/type_create.g.dart, lib/widgets/components/wallet_button/type_existing.g.dart
https://www.figma.com/file/7T7GiBEszjus4tpyOAiPaI/GNUS-FInal-Build?node-id=69%3A1891&mode=dev
=> Splash screen / wallet creation screen updated to match latest figma

lib/app/widgets/app_screen_with_header_mobile.dart, lib/onboarding/existing_wallet/view/import_security_screen.dart, lib/onboarding/existing_wallet/view/import_wallet_screen.dart, lib/onboarding/widgets/paste_field.dart, lib/onboarding/widgets/supported_existing_wallets.dart, lib/theme/genius_wallet_colors.g.dart, lib/theme/genius_wallet_text.dart, lib/widgets/components/text_entry_field_widget.g.dart, lib/widgets/components/wallet_card.g.dart
https://www.figma.com/file/7T7GiBEszjus4tpyOAiPaI/GNUS-FInal-Build?type=design&node-id=264-6807&mode=dev
https://www.figma.com/file/7T7GiBEszjus4tpyOAiPaI/GNUS-FInal-Build?type=design&node-id=265-6969&mode=dev
=> Import Wallet Style Updates

lib/dashboard/wallets/send/view/enter_wallet_address_screen.dart, lib/dashboard/wallets/send/view/not_enough_balance_screen.dart, lib/dashboard/wallets/send/view/transaction_details_screen.dart, lib/dashboard/wallets/view/wallet_details_screen.dart, lib/widgets/components/back_button_dashboard.g.dart, lib/widgets/components/continue_button/isactive_true.g.dart, lib/widgets/components/text_entry_field_widget.g.dart, lib/widgets/components/transaction_detail_tile.g.dart, lib/widgets/components/wallet_q_r_scan.g.dart
=> Send Crypto Screen Updates

lib/app/widgets/currency_dropdown.dart, lib/app/widgets/overlay/mobile_overlay.dart, lib/calculator/view/calculator_screen.dart, lib/widgets/components/coin_stats_card.g.dart, lib/widgets/components/conversion_result.g.dart, lib/widgets/components/currency_selector/mode_from.g.dart, lib/widgets/components/currency_selector/mode_to.g.dart, lib/widgets/components/enter_amount.g.dart, lib/widgets/components/enter_amount_widget.g.dart, lib/widgets/components/genius_appbar.g.dart, lib/widgets/components/header.g.dart
Routing issue here:
https://github.com/GeniusVentures/GeniusWallet/issues/54
=> Update the calculator screen styling

lib/markets/view/markets_screen.dart, lib/navigation/router.dart, lib/widgets/components/market_graph.g.dart
=> Update Markets Screen / Add Coming Soon to Missing Screens

lib/app/widgets/app_screen_with_header_desktop.dart, lib/app/widgets/desktop_body_container.dart, lib/onboarding/existing_wallet/view/import_security_screen.dart, lib/onboarding/existing_wallet/view/import_wallet_screen.dart, lib/onboarding/existing_wallet/view/legal_screen.dart, lib/onboarding/new_wallet/view/backup_phrase_screen.dart, lib/onboarding/new_wallet/view/recovery_phrase_screen.dart, lib/onboarding/new_wallet/view/verify_recovery_phrase_screen.dart, lib/onboarding/widgets/recovery_words.dart, lib/onboarding/widgets/supported_existing_wallets.dart, lib/widgets/components/custom/wallet_agreement_custom.dart, lib/widgets/components/recoveryword.g.dart, lib/widgets/components/registration_header.g.dart
update security, wallet, backup phrase, recovery phrase, recovery words, wallet agreement, and legal screens
=> Update desktop initial screens

lib/app/widgets/overlay/desktop_overlay.dart, lib/dashboard/home/view/home_screen.dart, lib/dashboard/home/widgets/wallet_distribution.dart, lib/dashboard/wallets/view/wallet_details_screen.dart, lib/main.dart, lib/theme/genius_wallet_consts.dart, lib/widgets/components/wallets_overview.g.dart, lib/widgets/desktop/asset_percentage_card.g.dart
Desktop dashboard path, sets up the presentation ( responsive'ish ), placeholders for transactions, asset distribution, and chart.
New:
Old:
=> Desktop Dashboard Updates

lib/app/widgets/desktop_container.dart, lib/dashboard/wallets/view/wallet_details_screen.dart, lib/dashboard/wallets/view/wallets_screen.dart, lib/main.dart, lib/widgets/components/add_wallet_block.g.dart, lib/widgets/components/transactions.g.dart, lib/widgets/desktop/asset_percentage_card.g.dart
Updates the wallet details screen for desktop, adds back button support, also adds "buy" button support for the buy buttons across the app.
New:
Before:
=> Wallet Details - Desktop

lib/app/widgets/desktop_container.dart, lib/dashboard/wallets/receive/view/receive_screen.dart, lib/dashboard/wallets/send/view/enter_wallet_address_screen.dart, lib/dashboard/wallets/send/view/not_enough_balance_screen.dart, lib/dashboard/wallets/send/view/transaction_details_screen.dart
New:
Old:
New:
Old:
New:
Old:
New:
Old:
Old:
=> Send Receive Screens - Desktop

lib/dashboard/transactions/view/transaction_information_screen.dart, lib/dashboard/transactions/view/transactions_screen.dart, lib/navigation/router.dart, lib/widgets/components/historic_transaction_detail_view.g.dart
=> Transaction Information Desktop

lib/dashboard/home/widgets/horizontal_wallets_scrollview.dart, lib/dashboard/wallets/view/wallet_details_screen.dart, lib/onboarding/existing_wallet/bloc/existing_wallet_bloc.dart, lib/onboarding/existing_wallet/bloc/existing_wallet_event.dart, lib/onboarding/existing_wallet/view/import_security_screen.dart, lib/onboarding/new_wallet/view/verify_recovery_phrase_screen.dart, lib/onboarding/view/keystore_tab_view.dart, lib/onboarding/widgets/supported_existing_wallets.dart, lib/widgets/components/wallet_preview.g.dart, packages/genius_api/lib/src/genius_api.dart, packages/genius_api/lib/tw/hd_wallet.dart, packages/genius_api/lib/types/security_type.dart
Adds the mnemonic import to the wallet.
Also added a delete function - we can remove / style it later.
=> Wallet Import / Delete

lib/onboarding/existing_wallet/view/import_security_screen.dart, packages/genius_api/lib/models/wallet.dart, packages/genius_api/lib/models/wallet.freezed.dart, packages/genius_api/lib/models/wallet.g.dart, packages/genius_api/lib/models/wallet_stored.dart, packages/genius_api/lib/models/wallet_stored.freezed.dart, packages/genius_api/lib/models/wallet_stored.g.dart, packages/genius_api/lib/src/genius_api.dart, packages/genius_api/lib/tw/any_address.dart, packages/genius_api/lib/tw/hd_wallet.dart, packages/genius_api/lib/tw/hd_wallet_impl.dart, packages/genius_api/lib/types/security_type.dart, packages/genius_api/lib/types/wallet_type.dart, packages/genius_api/pubspec.yaml, packages/local_secure_storage/lib/src/local_secure_storage_base.dart, packages/secure_storage/lib/src/secure_storage.dart, pubspec.lock, pubspec.yaml
This PR adds private key imports.
Derives address from private key.
Derives private key from menmonic.
Saves this to local storage.
Adds wallet types to saved wallets
=> Adds Private key imports

lib/app/bloc/overlay/navigation_overlay_cubit.dart, lib/app/widgets/hamburger_menu.dart, lib/app/widgets/overlay/desktop_overlay.dart, lib/app/widgets/overlay/destinations.dart, lib/dashboard/home/view/home_screen.dart, lib/dashboard/home/widgets/horizontal_wallets_scrollview.dart, lib/dashboard/transactions/view/transactions_screen.dart, lib/dashboard/wallets/view/wallets_screen.dart, lib/main.dart, lib/markets/view/markets_screen.dart, lib/onboarding/existing_wallet/view/import_security_screen.dart, lib/onboarding/view/address_tab_view.dart, lib/onboarding/view/keystore_tab_view.dart, lib/onboarding/view/phrase_tab_view.dart, lib/onboarding/view/private_key_tab_view.dart, lib/onboarding/widgets/paste_field.dart, lib/widgets/components/add_wallet_block.g.dart, lib/widgets/components/crypto_market_overview.g.dart, lib/widgets/components/custom/view_more_custom.dart, lib/widgets/components/custom/wallet_address_custom.dart, lib/widgets/components/genius_appbar.g.dart, lib/widgets/components/wallet_information.g.dart, lib/widgets/components/wallet_module.g.dart, lib/widgets/components/wallet_preview.g.dart, packages/genius_api/lib/src/genius_api.dart, packages/local_secure_storage/lib/src/local_secure_storage_base.dart, packages/secure_storage/lib/src/secure_storage.dart
fix header click to dashboard
fix routing issues, hamberger menu should select bottom navigation... not route, remove bottom padding on bottom nav bar
padding under bottom of transactions screen
fix overlap on market preview
responsive quantity in wallet details
wallet preview size fixes, responsiveness
wallet name / amount fixes, overflow handling, alignment wallet import screen improvements
- improve text box focus color
- improve paste button styling
- add paste for address field
- improve help text for inputs
=> Watch imports, Routing fixes, Styling fixes

lib/dashboard/home/widgets/horizontal_wallets_scrollview.dart, lib/dashboard/wallets/send/view/enter_wallet_address_screen.dart, lib/dashboard/wallets/send/view/transaction_details_screen.dart, lib/navigation/router.dart, lib/widgets/components/transaction_detail_tile.g.dart, lib/widgets/components/wallet_preview.g.dart, lib/widgets/components/wallet_type_icon.dart, lib/widgets/components/wallets_overview.g.dart, packages/genius_api/lib/web3/web3.dart, packages/local_secure_storage/lib/src/local_secure_storage_base.dart
- catch web 3 timeout
- dont delete wallets on error
- fix wallet preview display to look nicer.
=> fix web3 errors

lib/app/widgets/desktop_container.dart, lib/app/widgets/networks/network_dropdown.dart, lib/dashboard/home/view/home_screen.dart, lib/dashboard/home/widgets/horizontal_wallets_scrollview.dart, lib/dashboard/wallets/view/wallet_details_screen.dart, lib/dashboard/wallets/view/wallets_screen.dart, lib/main.dart, lib/onboarding/existing_wallet/view/import_security_screen.dart, lib/onboarding/view/wallet_creation_screen.dart, lib/widgets/components/add_wallet_block.g.dart, lib/widgets/components/copy_wallet_i_d.g.dart, lib/widgets/desktop/asset_percentage_card.g.dart, linux/CMakeLists.txt, packages/genius_api/lib/src/genius_api.dart, pubspec.lock
Fixes some issues in desktop wallet details, dashboard and import screens.
=> Fix Desktop, Import, wallet details, dashboard

lib/dashboard/home/view/home_screen.dart, lib/dashboard/home/widgets/horizontal_wallets_scrollview.dart, lib/widgets/components/custom/buy_button_custom.dart, lib/widgets/components/wallets_overview.g.dart
adds a responsive dashboard,
rewrites the wallet over section away from the Parabeac generation that was troublesome
adds the wallets overview as welll
=> Dashboard fixes

lib/app/bloc/app_bloc.dart, lib/app/widgets/app_screen_view.dart, lib/dashboard/home/view/home_screen.dart, lib/dashboard/home/widgets/containers.dart, lib/dashboard/home/widgets/transaction_filters.dart, lib/dashboard/home/widgets/transactions_slim_view.dart, lib/theme/genius_wallet_colors.g.dart, lib/widgets/components/wallets_overview.g.dart, packages/genius_api/lib/coin_gecko/coin_gecko_api.dart, packages/genius_api/lib/src/genius_api.dart, packages/genius_api/pubspec.yaml
Also:
* adds swipe down to refresh for desktop as well
* adds transaction filtering by type ( sent, received, all, mint )
* coming soon added to dashboard for missing features
=> Adds Transactions / Testnet Transactions to dashboard

README.md, lib/app/bloc/app_bloc.dart, lib/app/bloc/overlay/navigation_overlay_state.dart, lib/app/utils/breakpoints.dart, lib/app/widgets/hamburger_menu.dart, lib/app/widgets/overlay/desktop_overlay.dart, lib/app/widgets/overlay/destinations.dart, lib/app/widgets/overlay/responsive_overlay.dart, lib/dashboard/events/view/bloc/events_cubit.dart, lib/dashboard/events/view/events_screen.dart, lib/dashboard/home/view/home_screen.dart, lib/dashboard/home/widgets/transactions_slim_view.dart, lib/dashboard/news/view/bloc/news_cubit.dart, lib/dashboard/news/view/news_screen.dart, lib/dashboard/transactions/view/transactions_screen.dart, lib/dashboard/wallets/view/wallets_screen.dart, lib/markets/bloc/markets_cubit.dart, lib/markets/view/markets_screen.dart, lib/navigation/router.dart, lib/submit_job/view/submit_job_screen.dart, packages/genius_api/lib/coin_gecko/coin_gecko_api.dart, packages/genius_api/lib/src/genius_api.dart, pubspec.lock, pubspec.yaml
break point fixes, don't pass cg api key, fix some cubit errors
=> Job Upload Form for Testnet

lib/app/widgets/coins/view/coins_screen.dart, lib/dashboard/bridge/bridge_screen.dart, lib/navigation/router.dart, pubspec.lock, pubspec.yaml
update old ass router.
refresh coins / balance after bridge.
return from bridge to coins screen for now, to keep things up to date.
=> Bridge fixes

lib/dashboard/home/widgets/transactions_slim_view.dart, lib/onboarding/existing_wallet/view/import_security_screen.dart, lib/onboarding/new_wallet/view/backup_phrase_screen.dart, lib/onboarding/new_wallet/view/recovery_phrase_screen.dart, lib/onboarding/new_wallet/view/verify_recovery_phrase_screen.dart, lib/widgets/components/continue_button/isactive_false.g.dart, lib/widgets/components/continue_button/isactive_true.g.dart, lib/widgets/components/crypto_chart.g.dart, lib/widgets/components/market_graph.g.dart, lib/widgets/components/registration_header.g.dart, lib/widgets/components/wallet_card.g.dart, lib/widgets/components/wallet_module.g.dart
Cherry picked safus changes into develop
=> Visual Changes For IOS

lib/wallets/view/genius_wallet_details_screen.dart, lib/widgets/components/sgnus/sgnus_wallet.dart, packages/genius_api/lib/ffi/genius_api_ffi.dart, packages/genius_api/lib/src/genius_api.dart
- ffi functions to works on develop SDK
- GeniusWalletDetails now shows full value in Genius Tokens
- WalletPreview now shows only 3 decimals in Genius Tokens
Closes #107
=> dev_fix_point to develop: Update ffi with SDK in develop

lib/app/bloc/overlay/navigation_overlay_state.dart, lib/app/widgets/overlay/destinations.dart, lib/app/widgets/overlay/genius_tabbar.dart, lib/app/widgets/overlay/responsive_overlay.dart, lib/main.dart, lib/navigation/router.dart, lib/web/web_view_linux.dart, lib/web/web_view_mobile.dart, lib/web/web_view_screen.dart, lib/web/web_view_windows.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
Adds Webbrowser support to the wallet for Linux, Windows and Andoid/ IOS
=> Initial Web Browser Support

android/app/build.gradle, android/app/src/debug/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml, android/app/src/main/kotlin/ai/gnus/genius_wallet/MainActivity.kt, android/build.gradle, android/settings.gradle, cmake/CommonBuildParameters.cmake, lib/app/widgets/overlay/desktop_overlay.dart, lib/web/web_view_windows.dart, lib/widgets/components/genius_appbar.g.dart, macos/Flutter/GeneratedPluginRegistrant.swift, packages/genius_api/lib/ffi_bridge_prebuilt.dart, packages/genius_api/pubspec.yaml, pubspec.lock
- Adds some fixes for Windows web view
- Migrates our Android to use the newer plugin config
- Removes specific abi / builds support for all
- Fixes our package name to match and moves the activity file to the correct folder
- We can now run android version of the wallet without any thirdparty libs
=> Android / Web View Fixes

lib/account/account_dropdown_selector.dart, lib/chart/crypto_live_chart.dart, lib/chart/crypto_simple_chart.dart, lib/components/pulsing_skeleton.dart, lib/components/sgnus/sgnus_connection_widget.dart, lib/components/wallet_information.g.dart, lib/components/wallets_overview.g.dart, lib/dashboard/chart/dashboard_markets.dart, lib/dashboard/chart/markets_search_bar.dart, lib/dashboard/news/view/crypto_news_screen.dart, lib/dashboard/news/view/news_card.dart, lib/navigation/router.dart, lib/network/network_page.dart, lib/reown/reown_connect_button.dart, lib/theme/genius_wallet_colors.dart, lib/theme/theme.dart
Refactor UI components and charts for consistency
Added pulsing skeleton for zoom/pan  and network page for the showing network status
Improved news views by using custom future builder and added 2 colours for showing markets chart
=> Refactor UI components  and charts for consistency
